---
# SBOM2CVE Kafka Cluster
# Managed by Strimzi Kafka Operator
# For both local (K3s) and production (EKS/GKE/AKS) deployments

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sbom2cve-kafka
  namespace: sbom2cve
  labels:
    app: sbom2cve
    component: kafka
spec:
  # Kafka Broker Configuration
  kafka:
    version: 3.6.0
    replicas: 3

    # Listeners
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true

    # Kafka Configuration
    config:
      # Replication
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2

      # Protocol
      inter.broker.protocol.version: "3.6"

      # Performance
      num.network.threads: 8
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600

      # Log Retention
      log.retention.hours: 168  # 7 days default
      log.segment.bytes: 1073741824  # 1GB
      log.retention.check.interval.ms: 300000  # 5 minutes

      # Compaction
      log.cleaner.enable: true
      log.cleanup.policy: delete  # Override per-topic
      min.cleanable.dirty.ratio: 0.5

      # Auto-create topics (disable for production)
      auto.create.topics.enable: false

    # Storage
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
          class: standard  # Use default storage class

    # Resource Limits
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m

    # JVM Options
    jvmOptions:
      -Xms: 2048m
      -Xmx: 2048m

    # Metrics
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

  # Zookeeper Configuration
  zookeeper:
    replicas: 3

    # Storage
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: standard

    # Resource Limits
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

    # Metrics
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml

  # Entity Operator (Topic & User management)
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 500m

    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 500m

---
# Kafka Metrics ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: sbom2cve
  labels:
    app: sbom2cve
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
    # Kafka Broker metrics
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
       clientId: "$3"
       topic: "$4"
       partition: "$5"
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
       clientId: "$3"
       broker: "$4:$5"

  zookeeper-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
    # Zookeeper metrics
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
      name: "zookeeper_$2"
      type: GAUGE
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
      name: "zookeeper_$3"
      type: GAUGE
      labels:
        replicaId: "$2"

---
# Kafka Exporter for additional metrics
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: sbom2cve
  labels:
    app: kafka-exporter
spec:
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
  selector:
    app: kafka-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: sbom2cve
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          args:
            - --kafka.server=sbom2cve-kafka-bootstrap:9092
            - --web.listen-address=:9308
            - --log.level=info
          ports:
            - containerPort: 9308
              name: metrics
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
